# Generated by Django 5.0.2 on 2024-02-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_project_main_photo_alter_gallery_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="property_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_images",
                to="assets.property",
            ),
        ),
    ]
