# Generated by Django 5.0.2 on 2024-02-24 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_amenity_description_alter_gallery_property_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gallery",
            new_name="ImageGallery",
        ),
    ]
