# Generated by Django 5.0.2 on 2024-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_rename_gallery_imagegallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="location_image",
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="plot_layout",
            field=models.ImageField(blank=True, null=True, upload_to="project_plot/"),
        ),
    ]
