# Generated by Django 5.0.2 on 2024-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_remove_project_location_image_project_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
