# Generated by Django 5.0.2 on 2024-02-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_alter_project_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="plot_layout",
        ),
        migrations.CreateModel(
            name="ProjectPlotLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plot/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_plotlayout",
                        to="assets.project",
                    ),
                ),
            ],
        ),
    ]
