# Generated by Django 5.0.2 on 2024-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_remove_project_plot_layout_projectplotlayout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infratech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="InfraTechImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="infratech/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="location",
        ),
    ]
