# Generated by Django 5.0.2 on 2024-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_contactus_delete_features_delete_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="blogs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
