# Generated by Django 5.0.2 on 2024-02-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
