# Generated by Django 5.0.2 on 2024-02-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homegallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=155)),
                ("image", models.ImageField(upload_to="directors")),
                ("position", models.CharField(max_length=100, null=True)),
                (
                    "aboutus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors_images",
                        to="home.aboutus",
                    ),
                ),
            ],
        ),
    ]
