# Generated by Django 5.0.2 on 2024-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_aboutus_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="carousel/")),
            ],
        ),
    ]
