# Generated by Django 5.0.2 on 2024-02-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_carousel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="aboutus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directors",
                to="home.aboutus",
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
