# Generated by Django 5.0.2 on 2024-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_director_aboutus_alter_director_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(default=1, upload_to="about/"),
            preserve_default=False,
        ),
    ]
