# Generated by Django 5.0.2 on 2024-02-16 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_property_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="amenities",
        ),
    ]
